version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - farmnet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - farmnet

networks:
  farmnet:
